apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}-postgres
  ports:
      - port: {{ .Values.postgres.port }}
        targetPort: {{ .Values.postgres.port }}