kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-rabbitmq-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.rabbitMQ.path }}